Issue 1 create an entry - Scarlet Kim
Scarlet-K/code-journal pull request #5
Opened 2022-06-01 22:59 UTC by Scarlet-K

![issue-1-create](https://user-images.githubusercontent.com/103100017/171515185-15d299fb-4417-4f37-9a12-01fd231f3496.gif)

2022-06-01 23:34 UTC, codingcodymiller commented on js/data.js
> +  }
This should be happening when the page first loads, not right before it unloads.

2022-06-01 23:35 UTC, codingcodymiller commented on js/main.js
> +  formObj.nextEntryId = 0;
😱 

Why `0`? You should be using the `data.nextEntryId` property as the source of the id to apply to this entry. Also, `nextEntryId` is not an appropriate name for this property, since it is storing this entry's id, not the next entry id to use. You should name this property `entryId`

2022-06-02 00:12 UTC, Scarlet-K commented on index.html
> +    <h1 class="column-half">New Entry</h1>
When I add the row to the div with class "container", the form is no longer centered :(

2022-06-02 15:56 UTC, codingcodymiller requested changes

2022-06-02 15:56 UTC, codingcodymiller commented on index.html
> +          <p></p>
This empty `p` element can be removed

2022-06-02 15:56 UTC, codingcodymiller commented on js/data.js
> +  var dataJSON = JSON.parse(oldEntry);
What is `dataJSON`? You should be replacing the `data` variable's value.

2022-06-02 15:56 UTC, codingcodymiller commented on js/data.js
> +  dataJSON = JSON.stringify(data);
Same here, use `data`, not `dataJSON`

2022-06-02 17:23 UTC, codingcodymiller approved these changes

2022-06-04 20:05 UTC, merged